"""Interceptor helpers for the `atlas-richie-http` E2E suite.

中文
----
E2E 测试用的拦截器:这些拦截器**真的**会被 `HttpClient` /
`AsyncHttpClient` 装到责任链上,所以 E2E 走的是完整切面,而不是
绕开 `intercept` 链直接调底层 transport。

English
--------
Interceptors wired into the real `HttpClient` / `AsyncHttpClient`
pipelines during E2E:

- `RequestIdHeaderInterceptor` — copies the inbound `X-Request-Id`
  (auto-generated by the built-in request-id interceptor) into
  an in-memory record so the test can assert the chain fired.
- `HeaderInjectInterceptor` — adds an `X-E2E-Marker` header
  to every outbound request; the FastAPI app echoes it back via
  the response so tests can prove the outbound header was set
  on the wire.

These are deliberately tiny and side-effect-isolated.
"""

from __future__ import annotations

from typing import Awaitable, Callable

from atlas_richie.http import (
    HttpRequest,
    HttpResponse,
)

# `SyncNext` / `AsyncNext` are not part of the public API — they
# are aliases defined in `interceptors.py` for internal use. We
# mirror the type signatures locally so the test helpers do not
# have to reach into private module attributes.
SyncNext = Callable[[HttpRequest], HttpResponse]
AsyncNext = Callable[[HttpRequest], Awaitable[HttpResponse]]


def _header_value(headers, name: str) -> str | None:
    """Case-insensitive header lookup mirroring `models.header_value`.

    中文
    ----
    与 `atlas_richie.http.models.header_value` 行为一致的本地
    实现;避免在测试 helper 里 import 公共 API 未导出的工具函数。

    English
    --------
    Local implementation of the case-insensitive header lookup
    that lives privately in `models.py`. Keeping a copy here
    means the E2E helpers don't reach into non-public API
    names.
    """
    expected = name.casefold()
    for key, value in headers.items():
        if key.casefold() == expected:
            return value
    return None


class RequestIdCaptureInterceptor:
    """Capture the request-id that the built-in interceptor set.

    中文
    ----
    抓取 `_RequestIdInterceptor` 在出站请求上写的 `X-Request-Id`。
    业务代码只会看到 `record: list[str]`,E2E 断言它非空、且与
    实际请求一致即可。

    English
    --------
    Capture the `X-Request-Id` written by the built-in
    `_RequestIdInterceptor` on the outbound request so an E2E
    test can assert the chain really fired.
    """

    def __init__(self) -> None:
        self.record: list[str] = []

    def intercept(self, request: HttpRequest, proceed: SyncNext) -> HttpResponse:
        captured = _header_value(request.headers, "X-Request-Id")
        if captured is not None:
            self.record.append(captured)
        return proceed(request)


class AsyncRequestIdCaptureInterceptor:
    """Async counterpart of `RequestIdCaptureInterceptor`."""

    def __init__(self) -> None:
        self.record: list[str] = []

    async def intercept(self, request: HttpRequest, proceed: AsyncNext) -> HttpResponse:
        captured = _header_value(request.headers, "X-Request-Id")
        if captured is not None:
            self.record.append(captured)
        return await proceed(request)


class HeaderInjectInterceptor:
    """Inject `X-E2E-Marker` so the test can prove the header was on the wire.

    中文
    ----
    在每个出站请求上加 `X-E2E-Marker`。FastAPI 把它原样回写到响应
    头里,E2E 断言响应头出现这个标记,即可证明拦截器真的写到了
    HTTPX 的请求对象上。

    English
    --------
    Inject a fixed `X-E2E-Marker` header on every outbound request.
    The FastAPI app reflects it back in the response, so the test
    can prove the interceptor really wrote it onto the HTTPX
    request.
    """

    marker = "e2e-marker"

    def intercept(self, request: HttpRequest, proceed: SyncNext) -> HttpResponse:
        request = request.with_header("X-E2E-Marker", self.marker)
        response = proceed(request)
        return response


class AsyncHeaderInjectInterceptor:
    """Async counterpart of `HeaderInjectInterceptor`."""

    marker = "e2e-marker"

    async def intercept(self, request: HttpRequest, proceed: AsyncNext) -> HttpResponse:
        request = request.with_header("X-E2E-Marker", self.marker)
        response = await proceed(request)
        return response
